### ISSUE TITLE
Is there a tentative date for which this dataset will be released?

### ISSUE THREAD

**Issue by jequihua** [LEEClab/jaguar_movement#1]
I'm part of a research team at [CONABIO]( https://www.gob.mx/conabio) trying to simulate animal movement with agent based models.

This dataset would be of great use for us to calibrate models for jaguars.

Any info would be deeply appreciated!

**Comment by miltinhoastronauta** [comment]
Hi there,

please, write to miltinho.astronauta@gmail.com please.

best



Miltinho  - mcr@rc.unesp.br
Spatial Ecology and Conservation lab - LEEC
Departament of Ecology - UNESP - Rio Claro/SP
Av. 24A, 1515 - Bela Vista
13506-900, Rio Claro, SP, Brasil
Fone: +55-19 3526.9680 (lab)
   LEEC website <http://leec.eco.br/> |  Lattes
<http://lattes.cnpq.br/4158685235743119> |  Google citations
<http://scholar.google.com/citations?user=OWX_2eAAAAAJ> |  Depto Ecologia
<http://ib.rc.unesp.br/#!/departamentos/ecologia/> |  PG Eco&Biodiv
<http://ib.rc.unesp.br/#!/departamentos/ecologia/pos-graduacao-em-ecologia-e-biodiversidade/>
|
Orcid  0000-0002-4312-202X


2018-05-15 20:08 GMT-03:00 Julian <notifications@github.com>:

**Comment by bniebuhr** [comment]
Hi there,

I am not sure if this was already solved, but here is the link for the published data:
https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.2379

We're also going to update it here today.

Best,
Bernardo Niebuhr
